#!/usr/bin/env python
#
# Hack utility to show the relationship from a boosterpack in a
# platform to MCU functional capabilities.
#
# Use this to quickly discover things like the fact the Fraunchpad
# doesn't align with RF boosterpacks.

import sys
import os
import os.path

sys.path.append(os.path.join(os.environ['BSP430_ROOT'], 'maintainer', 'lib', 'python'))
import bsp430.pinmap

rfem = None
#rfem ='cc3000em'
#rfem ='cc110xemk'
#boosterpack = None
boosterpack = 'cc3000boost'
#boosterpack = 'ccem'
#boosterpack = 'senshub'
boosterpack = 'battpack'
platform = 'exp430f5529lp'
#platform = 'exp430fr5739'
mcu = 'msp430f5529'
#mcu = 'msp430fr5739'

maps = []

if rfem is not None:
    print('RFEM %s' % (rfem,))
    m = bsp430.pinmap.GenerateMap('rfem', rfem)
    #m = dict([(v,k) for (k,v) in m.iteritems()])
    maps.append(m)

if boosterpack is not None:
    print('Boosterpack %s' % (boosterpack,))
    m = bsp430.pinmap.GenerateMap('boosterpack', boosterpack)
    m = dict([(v,k) for (k,v) in m.iteritems()])
    maps.append(m)

if platform is not None:
    print('Platform %s' % (platform,))
    m = bsp430.pinmap.GenerateMap('platform', platform)
    maps.append(m)

if mcu is not None:
    print('MCU %s' % (mcu,))
    m = {}
    for ln in bsp430.pinmap.GenerateLines('mcu', mcu):
        elts = ln.split()
        pin = bsp430.pinmap.CreateInstance(elts.pop(0))
        if pin is None:
            continue
        m[pin] = list(map(bsp430.pinmap.CreateInstance, elts))
    maps.append(m)

for hdr in sorted(maps[0].keys()):
    line = [str(hdr)]
    for m in maps:
        if hdr is None:
            break
        pin = m.get(hdr)
        if pin is None:
            line.append('-')
            break
        try:
            line.extend(map(str, pin))
            hdr = None
        except TypeError:
            line.append(str(pin))
            hdr = pin
    print('\t'.join(line))
    '''
    pin = p.get(hdr)
    mv = m.get(pin)
    if mv is None:
        mvs = '-'
    else:
        mvs = '\t'.join(map(str, mv))
    print('{}\t{}\t{}'.format(hdr, pin, mvs))
    '''

# Local Variables:
# mode: python
# End:
