PLATFORM ?= trxeb
MODULES=$(MODULES_PLATFORM)
MODULES += $(MODULES_CONSOLE)
MODULES += periph/timer
MODULES += utility/unittest
MODULES += utility/uptime
SRC=main.c
include $(BSP430_ROOT)/make/Makefile.common
