/* Copyright 2012-2014, Peter A. Bigot
 *
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice,
 *   this list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of the software nor the names of its contributors may be
 *   used to endorse or promote products derived from this software without
 *   specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

/** @file
 * @brief Platform-specific BSP430 configuration directives for <a href="http://www.ti.com/tool/cc1125dk">MSP-TRXEB</a>
 *
 * @homepage http://github.com/pabigot/bsp430
 * @copyright Copyright 2012-2014, Peter A. Bigot.  Licensed under <a href="http://www.opensource.org/licenses/BSD-3-Clause">BSD-3-Clause</a>
 */

#ifndef BSP430_PLATFORM_TRXEB_BSP430_CONFIG_H
#define BSP430_PLATFORM_TRXEB_BSP430_CONFIG_H

/** @cond DOXYGEN_EXCLUDE */

/* Platform has custom LED implementation */
#ifndef configBSP430_LED_USE_COMMON
#define configBSP430_LED_USE_COMMON 0
#endif /* configBSP430_LED_USE_COMMON */

/* Use native USCI5 for genericized serial port unless told not to */
#ifndef configBSP430_SERIAL_USE_USCI5
#define configBSP430_SERIAL_USE_USCI5 1
#endif /* configBSP430_SERIAL_USE_USCI5 */

/* Enable buttons as requested */
#if (configBSP430_PLATFORM_BUTTON0 - 0) || (configBSP430_PLATFORM_BUTTON1 - 0)
#if !defined(configBSP430_HAL_PORT2)
#define configBSP430_HAL_PORT2 1
#else /* configBSP430_HAL_PORT2 */
#if (configBSP430_PLATFORM_BUTTON0 - 0) && ! defined(configBSP430_HPL_PORT2)
#define configBSP430_HPL_PORT2 1
#endif /* BUTTON0 */
#if (configBSP430_PLATFORM_BUTTON1 - 0) && ! defined(configBSP430_HPL_PORT2)
#define configBSP430_HPL_PORT2 1
#endif /* BUTTON1 */
#endif /* configBSP430_HAL_PORT2 */
#endif /* configBSP430_PLATFORM_BUTTON[01] */

/* What to use as a console */
#if (configBSP430_CONSOLE - 0)
#ifndef BSP430_CONSOLE_SERIAL_PERIPH_CPPID
#define BSP430_CONSOLE_SERIAL_PERIPH_CPPID BSP430_PERIPH_CPPID_USCI5_A1
#endif /* BSP430_CONSOLE_SERIAL_PERIPH_CPPID */
#endif /* configBSP430_CONSOLE */

/* How to use ACLK as a capture/compare input source */
/* Settings for TB0: T0B6 ccis=1 ; clk P4.7 ; cc0 P4.0 ; cc1 P4.1 */
#if (configBSP430_TIMER_CCACLK - 0)
#ifndef BSP430_TIMER_CCACLK_PERIPH_CPPID
#define BSP430_TIMER_CCACLK_PERIPH_CPPID BSP430_PERIPH_CPPID_TB0
#endif /* BSP430_TIMER_CCACLK_PERIPH_CPPID */
#ifndef BSP430_TIMER_CCACLK_CLK_PORT_PERIPH_CPPID
#define BSP430_TIMER_CCACLK_CLK_PORT_PERIPH_CPPID BSP430_PERIPH_CPPID_PORT4
#endif /* BSP430_TIMER_CCACLK_CLK_PORT_PERIPH_CPPID */
#ifndef BSP430_TIMER_CCACLK_CC0_PORT_PERIPH_CPPID
#define BSP430_TIMER_CCACLK_CC0_PORT_PERIPH_CPPID BSP430_PERIPH_CPPID_PORT4
#endif /* BSP430_TIMER_CCACLK_CC0_PORT_PERIPH_CPPID */
#ifndef BSP430_TIMER_CCACLK_CC1_PORT_PERIPH_CPPID
#define BSP430_TIMER_CCACLK_CC1_PORT_PERIPH_CPPID BSP430_PERIPH_CPPID_PORT4
#endif /* BSP430_TIMER_CCACLK_CC1_PORT_PERIPH_CPPID */
#endif /* configBSP430_TIMER_CCACLK */

/* !BSP430! insert=rfem_config platform=trxeb mcu=msp430f5438a */
/* BEGIN AUTOMATICALLY GENERATED CODE---DO NOT MODIFY [rfem_config] */
#if (configBSP430_RFEM - 0)
#define BSP430_RFEM_SERIAL_PERIPH_CPPID BSP430_PERIPH_CPPID_USCI5_B0
#define configBSP430_SERIAL_ENABLE_SPI 1
#define configBSP430_HAL_USCI5_B0 1
#define BSP430_RFEM_RF1P3_PORT_PERIPH_CPPID BSP430_PERIPH_CPPID_PORT1
#define BSP430_RFEM_RF1P3_TIMER_PERIPH_CPPID BSP430_PERIPH_CPPID_TA0
#define BSP430_RFEM_RF1P4_PORT_PERIPH_CPPID BSP430_PERIPH_CPPID_PORT1
#define BSP430_RFEM_RF1P4_TIMER_PERIPH_CPPID BSP430_PERIPH_CPPID_TA0
#define BSP430_RFEM_RF1P5_PORT_PERIPH_CPPID BSP430_PERIPH_CPPID_PORT8
#define BSP430_RFEM_RF1P5_TIMER_PERIPH_CPPID BSP430_PERIPH_CPPID_TA0
#define BSP430_RFEM_RF1P6_PORT_PERIPH_CPPID BSP430_PERIPH_CPPID_PORT1
#define BSP430_RFEM_RF1P6_TIMER_PERIPH_CPPID BSP430_PERIPH_CPPID_TA0
#define BSP430_RFEM_RF1P7_PORT_PERIPH_CPPID BSP430_PERIPH_CPPID_PORT3
#define BSP430_RFEM_RF1P9_PORT_PERIPH_CPPID BSP430_PERIPH_CPPID_PORT3
#define BSP430_RFEM_RF1P10_PORT_PERIPH_CPPID BSP430_PERIPH_CPPID_PORT1
#define BSP430_RFEM_RF1P11_PORT_PERIPH_CPPID BSP430_PERIPH_CPPID_PORT8
#define BSP430_RFEM_RF1P11_TIMER_PERIPH_CPPID BSP430_PERIPH_CPPID_TA0
#define BSP430_RFEM_RF1P12_PORT_PERIPH_CPPID BSP430_PERIPH_CPPID_PORT1
#define BSP430_RFEM_RF1P12_TIMER_PERIPH_CPPID BSP430_PERIPH_CPPID_TA0
#define BSP430_RFEM_RF1P14_PORT_PERIPH_CPPID BSP430_PERIPH_CPPID_PORT3
#define BSP430_RFEM_RF1P15_PORT_PERIPH_CPPID BSP430_PERIPH_CPPID_PORT8
#define BSP430_RFEM_RF1P15_TIMER_PERIPH_CPPID BSP430_PERIPH_CPPID_TA0
#define BSP430_RFEM_RF1P16_PORT_PERIPH_CPPID BSP430_PERIPH_CPPID_PORT3
#define BSP430_RFEM_RF1P17_PORT_PERIPH_CPPID BSP430_PERIPH_CPPID_PORT8
#define BSP430_RFEM_RF1P17_TIMER_PERIPH_CPPID BSP430_PERIPH_CPPID_TA1
#define BSP430_RFEM_RF1P18_PORT_PERIPH_CPPID BSP430_PERIPH_CPPID_PORT3
#define BSP430_RFEM_RF1P20_PORT_PERIPH_CPPID BSP430_PERIPH_CPPID_PORT3
#define BSP430_RFEM_RF2P15_PORT_PERIPH_CPPID BSP430_PERIPH_CPPID_PORT8
#define BSP430_RFEM_RF2P15_TIMER_PERIPH_CPPID BSP430_PERIPH_CPPID_TA0
#define BSP430_RFEM_RF2P17_PORT_PERIPH_CPPID BSP430_PERIPH_CPPID_PORT8
#define BSP430_RFEM_RF2P17_TIMER_PERIPH_CPPID BSP430_PERIPH_CPPID_TA0
#define BSP430_RFEM_RF2P18_PORT_PERIPH_CPPID BSP430_PERIPH_CPPID_PORT1
#define BSP430_RFEM_RF2P18_TIMER_PERIPH_CPPID BSP430_PERIPH_CPPID_TA0
#define BSP430_RFEM_RF2P19_PORT_PERIPH_CPPID BSP430_PERIPH_CPPID_PORT1
#endif /* configBSP430_RFEM */
/* END AUTOMATICALLY GENERATED CODE [rfem_config] */
/* !BSP430! end=rfem_config */

#if (configBSP430_PLATFORM_TRXEB_ALS - 0)
#ifndef configBSP430_HPL_PORT6
#define configBSP430_HPL_PORT6 1
#endif /* configBSP430_HPL_PORT6 */
#endif /* configBSP430_PLATFORM_TRXEB_ALS */

#if (configBSP430_PLATFORM_TRXEB_ACCEL - 0)
/* Accelerometer is on IO_SPI1 */
#define configBSP430_PLATFORM_TRXEB_IO_SPI1 1
/* P6.1 is accelerometer power */
#ifndef configBSP430_HPL_PORT6
#define configBSP430_HPL_PORT6 1
#endif /* configBSP430_HPL_PORT6 */
/* P8.7 is accelerometer CSn */
#ifndef configBSP430_HPL_PORT8
#define configBSP430_HPL_PORT8 1
#endif /* configBSP430_HPL_PORT8 */
/* Accelerometer IRQ is P2.0 */
#if (configBSP430_PLATFORM_TRXEB_ACCEL_IRQ - 0)
#ifndef configBSP430_HAL_PORT2
#define configBSP430_HAL_PORT2 1
#endif /* configBSP430_HAL_PORT2 */
#endif /* configBSP430_PLATFORM_TRXEB_ACCEL_IRQ */
#endif /* configBSP430_PLATFORM_TRXEB_ACCEL */

#if (configBSP430_PLATFORM_M25P - 0)
/* Flash is on IO_SPI0 */
#define configBSP430_PLATFORM_TRXEB_IO_SPI0 1
/* P7.6 is FLASH_PWR */
#ifndef configBSP430_HPL_PORT7
#define configBSP430_HPL_PORT7 1
#endif /* configBSP430_HPL_PORT7 */
/* P8.6 is FLASH_CSn */
#ifndef configBSP430_HPL_PORT8
#define configBSP430_HPL_PORT8 1
#endif /* configBSP430_HPL_PORT8 */
#endif /* configBSP430_PLATFORM_M25P */

#if (configBSP430_UTILITY_U8GLIB - 0) && (! defined(configBSP430_PLATFORM_TRXEB_LCD))
#define configBSP430_PLATFORM_TRXEB_LCD 1
#endif /* U8GLIB */

#if (configBSP430_PLATFORM_TRXEB_LCD - 0)
/* LCD is on IO_SPI0 */
#define configBSP430_PLATFORM_TRXEB_IO_SPI0 1
/* PWR (P7.7) and RSTn (P7.3) */
#ifndef configBSP430_HPL_PORT7
#define configBSP430_HPL_PORT7 1
#endif /* configBSP430_HPL_PORT7 */
/* CSn (P9.6) and A0 (P9.7) */
#ifndef configBSP430_HPL_PORT9
#define configBSP430_HPL_PORT9 1
#endif /* configBSP430_HPL_PORT9 */
#endif /* configBSP430_PLATFORM_TRXEB_LCD */

#if (configBSP430_PLATFORM_TRXEB_IO_SPI0 - 0)
#define configBSP430_SERIAL_ENABLE_SPI 1
#define configBSP430_HAL_USCI5_B2 1
#endif /* configBSP430_PLATFORM_TRXEB_IO_SPI0 */

#if (configBSP430_PLATFORM_TRXEB_IO_SPI1 - 0)
#define configBSP430_SERIAL_ENABLE_SPI 1
#define configBSP430_HAL_USCI5_A2 1
#endif /* configBSP430_PLATFORM_TRXEB_IO_SPI1 */

/** @endcond */

#endif /* BSP430_PLATFORM_TRXEB_BSP430_CONFIG_H */
