# The MSP430F5438a is soldered in.
MCU=msp430f5438a

MSPDEBUG_DRIVER=-j uif
# Custom LED implementation in platform module
MODULES_LED=platform/$(PLATFORM)/platform
# UCS needs CCACLK for DCO configuration
MODULES_CLOCK=periph/ucs periph/timer
MODULES_PLATFORM_SERIAL=periph/usci5

# The TRxEB board has an M25P20E serial flash
MODULES_M25P=$(MODULES_PLATFORM_SERIAL) periph/port utility/m25p

# U8GLIB uses vertical 1-bit pixels
PLATFORM_U8G_PB_C=$(U8GLIB_CSRC)/u8g_pb8v1.c
