PLATFORM ?= exp430fr5739
TEST_PLATFORMS = exp430g2 exp430fr5739 trxeb
MODULES=$(MODULES_PLATFORM)
MODULES += $(MODULES_CONSOLE)
MODULES += utility/unittest
MODULES += periph/port
SRC=main.c
include $(BSP430_ROOT)/make/Makefile.common
