PLATFORM = exp430f5438
MODULES=$(MODULES_PLATFORM)
MODULES += $(MODULES_UPTIME)
MODULES += $(MODULES_CONSOLE)
MODULES += modules/sys
MODULES += modules/flash
SRC=main.c
include $(BSP430_ROOT)/examples/Makefile.common
