PLATFORM ?= trxeb
MODULES=$(MODULES_PLATFORM)
MODULES += $(MODULES_UPTIME)
MODULES += $(MODULES_CONSOLE)
MODULES += periph/timer periph/port
SRC=main.c
include $(BSP430_ROOT)/examples/Makefile.common
