PLATFORM ?= exp430fr5739
MODULES=$(MODULES_PLATFORM)
MODULES += $(MODULES_UPTIME)
MODULES += $(MODULES_CONSOLE)
MODULES += periph/pmm periph/sys
SRC=main.c
include $(BSP430_ROOT)/make/Makefile.common
