# Somebody might put a msp430f5438 (non-A) in this, if they like using
# bad silicon.
MCU ?= msp430f5438a

MSPDEBUG_DRIVER=-j uif
# UCS needs CCACLK for DCO configuration
MODULES_CLOCK=periph/ucs periph/timer
MODULES_PLATFORM_SERIAL=periph/usci5
