# Somebody might put a msp430f5438 (non-A) in this, if they like using
# bad silicon.
MCU ?= msp430f5438a

MSPDEBUG_DRIVER=-j uif
# UCS needs CCACLK for DCO configuration
# MCLK configurations need PMM module
MODULES_CLOCK=periph/ucs periph/timer periph/pmm
MODULES_PLATFORM_SERIAL=periph/usci5

# U8GLIB uses horizontal 2-bit pixels
PLATFORM_U8G_PB_C=$(U8GLIB_CSRC)/u8g_pb8h2.c
