PLATFORM ?= trxeb
MODULES=$(MODULES_PLATFORM)
MODULES += $(MODULES_CONSOLE)
MODULES += $(MODULES_EUI64) utility/eui64
MODULES += utility/unittest
SRC=main.c
include $(BSP430_ROOT)/examples/Makefile.common
