PLATFORM ?= exp430fr5739
TEST_PLATFORMS_EXCLUDE = exp430fr5739 exp430g2
MODULES=$(MODULES_PLATFORM)
MODULES += $(MODULES_CONSOLE)
MODULES += utility/unittest
MODULES += resource
SRC=main.c
include $(BSP430_ROOT)/examples/Makefile.common
