PLATFORM ?= exp430fr5739
MODULES=$(MODULES_PLATFORM)
MODULES += $(MODULES_CONSOLE)
MODULES += $(MODULES_UPTIME)
MODULES += utility/unittest
MODULES += periph/timer
MODULES += periph/port
SRC=main.c
include $(BSP430_ROOT)/examples/Makefile.common
