PLATFORM=trxeb
TEST_PLATFORMS=trxeb
MODULES=$(MODULES_PLATFORM)
MODULES += $(MODULES_CONSOLE)
MODULES += $(MODULES_UPTIME)
MODULES += utility/unittest
MODULES += periph/timer
MODULES += periph/port
SRC=main.c
include $(BSP430_ROOT)/make/Makefile.common
